include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"

  errors:
    # Downgrade these to warnings (optional)
    missing_return: warning
    dead_code: warning
    unnecessary_null_comparison: warning

linter:
  rules:
    # --- Commonly useful ---
    avoid_print: true # use debugPrint or proper logging
    prefer_const_constructors: true # encourage const where possible
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true # make variables final if never reassigned
    prefer_single_quotes: true # consistency in strings
    always_use_package_imports: true # avoid relative imports
    avoid_unnecessary_containers: true
    unnecessary_this: true
    avoid_redundant_argument_values: true

    # --- Async / Error handling ---
    avoid_void_async: true
    unawaited_futures: true # don’t forget await
    cancel_subscriptions: true
    close_sinks: true

    # --- Style & Safety ---
    curly_braces_in_flow_control_structures: true
    avoid_types_on_closure_parameters: true
    unnecessary_lambdas: true
    prefer_interpolation_to_compose_strings: true
